# Site settings
title: Aron blog 
email: kymowind@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    nihao
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kymo.github.io" # the base hostname & protocol for your site
twitter_username: kymo
github_username: aron
encoding: utf-8
# Build settings
markdown: kramdown
